version: '3'

services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    ports:
      - "8080:8080"
    volumes:
      - ./jenkins_home:/var/jenkins_home
    networks:
      - net
  
  db_host:
    container_name: db_host
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=1234"
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - net

  cent_os:
    container_name: cent_os
    image: centssh
    networks:
      - net

networks:
  net: